#!/usr/bin/env bash
#
# Summary: Run an executable with the selected kubectl version
#
# Usage: kubectlenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected kubectl
# version's `bin' directory is at the front.
#
# For example, if the currently selected kubectl version is 0.7.0:
#   kubectlenv exec plan
#
# is equivalent to:
#   PATH="$KUBECTLENV_ROOT/versions/0.7.0/bin:$PATH" kubectl plan

set -e
[ -n "${KUBECTLENV_DEBUG}" ] && set -x

export KUBECTLENV_VERSION="$(kubectlenv-version-name)"
KUBECTL_BIN_PATH="${KUBECTLENV_ROOT}/versions/${KUBECTLENV_VERSION}/kubectl"
export PATH="${KUBECTL_BIN_PATH}:${PATH}"
"${KUBECTL_BIN_PATH}" "${@}"
