#!/usr/bin/env bash

[ -n "${KUBECTLENV_DEBUG}" ] && set -x
source "${KUBECTLENV_ROOT}/libexec/helpers"

[ "${#}" -gt 1 ] && error_and_die "usage: kubectlenv install [<version>]"

declare version_requested version regex

if [ -z "${1}" ]; then
  version_file="$(kubectlenv-version-file)"
  if [ "${version_file}" != "${KUBECTLENV_ROOT}/version" ]; then
    version_requested="$(cat "${version_file}" || true)"
  fi
else
  version_requested="${1}"
fi

if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
  version="${version_requested%%\:*}"
  regex="${version_requested##*\:}"
elif [[ "${version_requested}" =~ ^latest$ ]]; then
  version="${version_requested}"
  regex=""
else
  version="${version_requested}"
  regex="^${version_requested}$"
fi

[ -n "${version}" ] || error_and_die "Version is not specified"
version="$(kubectlenv-list-remote | grep -e "${regex}" | head -n 1)"
[ -n "${version}" ] || error_and_die "No versions matching '${1}' found in remote"

dst_path="${KUBECTLENV_ROOT}/versions/${version}"
if [ -f "${dst_path}/kubectl" ]; then
  echo "kubectl v${version} is already installed"
  exit 0
fi

version_url="https://storage.googleapis.com/kubernetes-release/release/v${version}/bin/$(KUBECTL_platform)"
exe_name="kubectl"
(( "$?" )) && exit $?

info "Installing kubectl v${version}"

# Create a local temporary directory for downloads
download_tmp="$(mktemp -d KUBECTLENV_download.XXXXXX)" || error_and_die "Unable to create temporary download directory in $(pwd)"
# Clean it up in case of error
trap "rm -rf ${download_tmp}" EXIT;

info "Downloading release from ${version_url}/${exe_name}"
curlw -# -f -L -o "${download_tmp}/${exe_name}" "${version_url}/${exe_name}" || error_and_die "Download failed"

mkdir -p "${dst_path}" || error_and_die "Failed to make directory ${dst_path}"
cp "${download_tmp}/${exe_name}" "${dst_path}/kubectl" || error_and_die "Copy of ${exe_name} from ${download_tmp} to ${dst_path} failed"
chmod a+x "${dst_path}/kubectl" || error_and_die "Unable to set execute on ${dst_path}/kubectl"

info "Installation of kubectl v${version} successful"
kubectlenv-use "$version"

