#!/usr/bin/env bash

[ -n "${KUBECTLENV_DEBUG}" ] && set -x

echo "Usage: kubectlenv <command> [<options>]

Commands:
   install       Install a specific version of kubectl
   use           Switch a version to use
   uninstall     Uninstall a specific version of kubectl
   list          List all installed versions
   list-remote   List all installable versions
"
