#!/usr/bin/env bash

[ -n "${KUBECTLENV_DEBUG}" ] && set -x
source "${KUBECTLENV_ROOT}/libexec/helpers"

[ ${#} -ne 1 ] && error_and_die "usage: kubectlenv use <version>"

declare version_requested version regex

version_requested="${1}"

if [[ "${version_requested}" =~ ^min-required$ ]]; then
  echo "Detecting minimal required version..."
  found_min_required="$(kubectlenv-min-required)"

  if [[ $? -eq 0 ]]; then
      echo "Min required version is detected as ${found_min_required}"
      version_requested=${found_min_required}
  else
    exit 1
  fi
fi

if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
  version="${version_requested%%\:*}"
  regex="${version_requested##*\:}"
elif [[ "${version_requested}" =~ ^latest$ ]]; then
  version="${version_requested}"
  regex=""
else
  version="${version_requested}"
  regex="^${version_requested}$"
fi

[ -d "${KUBECTLENV_ROOT}/versions" ] \
  || error_and_die "No versions of kubectl installed. Please install one with: kubectlenv install"

version="$(\ls "${KUBECTLENV_ROOT}/versions" \
  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
  | grep -e "${regex}" \
  | head -n 1
)"

[ -n "${version}" ] || error_and_die "No installed versions of kubectl matched '${1}'"

target_path=${KUBECTLENV_ROOT}/versions/${version}
[ -f "${target_path}/kubectl" ] \
  || error_and_die "Version directory for ${version} is present, but the kubectl binary is not! Manual intervention required."
[ -x "${target_path}/kubectl" ] \
  || error_and_die "Version directory for ${version} is present, but the kubectl binary is not executable! Manual intervention required. "

info "Switching to v${version}"
echo "${version}" > "$(kubectlenv-version-file)" || error_and_die "'switch to v${version} failed'"
kubectl version --client=true 1>/dev/null || error_and_die "'kubectl version client' failed. Something is seriously wrong"
info "Switching completed"
